/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paquete;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static paquete.Principal.cajaIdRest;

/**
 *
 * @author OTTONIEL CAMPOS
 */
public class VentanaDVR extends javax.swing.JFrame {

    public int idRestDvr;

    public void setIdRestDvr(int idRestDvr) {
        System.out.println(idRestDvr + "Valor dentro del set");
        this.idRestDvr = idRestDvr;
    }

    public VentanaDVR() {
        initComponents();
        mostrarTablaDvr(idRestDvr);
        
        cajaIdDvr.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDvr = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cajaIP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cajaUAdmin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cajaPAdmin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cajaUAlejandro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cajaPAlejandro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cajaUMario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cajaUGerente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cajaPGerente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cajaUOtro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cajaPOtro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cajaMarca = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cajaModelo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cajaPMario = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cajaSerie = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cajaUVicente = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cajaGrabacion = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cajaCAnalogas = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cajaDiscos = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cajaCIP = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        cajaPVicente = new javax.swing.JTextField();
        botonIngresoRest = new javax.swing.JButton();
        botonUpDateDvr = new javax.swing.JButton();
        botonBorrarDvr = new javax.swing.JButton();
        cajaIdDvr = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        cajaTipoCamara = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        cajaUsuarioCamara = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cajaIpCamara = new javax.swing.JTextField();
        cajaPassCamara = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1700, 800));
        setPreferredSize(new java.awt.Dimension(1344, 700));

        tablaDvr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "IP", "U.Admin", "P.Admin", "U.Ale", "P.Ale", "U.Mario", "P.Mario", "U.Vic", "P.Vic", "U.Ger", "P.Ger", "U.Otro", "P.Otro", "Marca", "Modelo", "Serie", "Capacidad Grabacion", "Capacidad Discos", "C. Analogas", "C. Digitales"
            }
        ));
        tablaDvr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDvrMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaDvr);

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cargar Tabla");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("IP:");

        cajaIP.setMinimumSize(new java.awt.Dimension(150, 25));
        cajaIP.setPreferredSize(new java.awt.Dimension(150, 25));
        cajaIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaIPActionPerformed(evt);
            }
        });

        jLabel2.setText("U-Admin:");

        cajaUAdmin.setMinimumSize(new java.awt.Dimension(100, 25));
        cajaUAdmin.setPreferredSize(new java.awt.Dimension(100, 25));
        cajaUAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaUAdminActionPerformed(evt);
            }
        });

        jLabel3.setText("P-Admin:");

        cajaPAdmin.setMinimumSize(new java.awt.Dimension(100, 25));
        cajaPAdmin.setPreferredSize(new java.awt.Dimension(100, 25));
        cajaPAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaPAdminActionPerformed(evt);
            }
        });

        jLabel4.setText("U-Alejandro");

        cajaUAlejandro.setMinimumSize(new java.awt.Dimension(100, 25));
        cajaUAlejandro.setPreferredSize(new java.awt.Dimension(100, 25));
        cajaUAlejandro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaUAlejandroActionPerformed(evt);
            }
        });

        jLabel5.setText("P-Alejandro");

        cajaPAlejandro.setMinimumSize(new java.awt.Dimension(100, 25));
        cajaPAlejandro.setPreferredSize(new java.awt.Dimension(100, 25));
        cajaPAlejandro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaPAlejandroActionPerformed(evt);
            }
        });

        jLabel6.setText("U-Mario");

        cajaUMario.setMinimumSize(new java.awt.Dimension(100, 25));
        cajaUMario.setPreferredSize(new java.awt.Dimension(100, 25));
        cajaUMario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaUMarioActionPerformed(evt);
            }
        });

        jLabel7.setText("U-Gerente");

        cajaUGerente.setMinimumSize(new java.awt.Dimension(100, 25));
        cajaUGerente.setPreferredSize(new java.awt.Dimension(100, 25));
        cajaUGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaUGerenteActionPerformed(evt);
            }
        });

        jLabel8.setText("P-Gerente");

        cajaPGerente.setMinimumSize(new java.awt.Dimension(100, 25));
        cajaPGerente.setPreferredSize(new java.awt.Dimension(100, 25));
        cajaPGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaPGerenteActionPerformed(evt);
            }
        });

        jLabel9.setText("U-Otro");

        cajaUOtro.setMinimumSize(new java.awt.Dimension(100, 25));
        cajaUOtro.setPreferredSize(new java.awt.Dimension(100, 25));
        cajaUOtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaUOtroActionPerformed(evt);
            }
        });

        jLabel10.setText("P-Otro");

        cajaPOtro.setMinimumSize(new java.awt.Dimension(100, 25));
        cajaPOtro.setPreferredSize(new java.awt.Dimension(100, 25));
        cajaPOtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaPOtroActionPerformed(evt);
            }
        });

        jLabel11.setText("Marca");

        cajaMarca.setMinimumSize(new java.awt.Dimension(150, 25));
        cajaMarca.setPreferredSize(new java.awt.Dimension(150, 25));
        cajaMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaMarcaActionPerformed(evt);
            }
        });

        jLabel12.setText("Modelo");

        cajaModelo.setMinimumSize(new java.awt.Dimension(150, 25));
        cajaModelo.setPreferredSize(new java.awt.Dimension(150, 25));
        cajaModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaModeloActionPerformed(evt);
            }
        });

        jLabel13.setText("P-Mario");

        cajaPMario.setMinimumSize(new java.awt.Dimension(100, 25));
        cajaPMario.setPreferredSize(new java.awt.Dimension(100, 25));
        cajaPMario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaPMarioActionPerformed(evt);
            }
        });

        jLabel14.setText("Serie");

        cajaSerie.setMinimumSize(new java.awt.Dimension(150, 25));
        cajaSerie.setPreferredSize(new java.awt.Dimension(150, 25));
        cajaSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaSerieActionPerformed(evt);
            }
        });

        jLabel15.setText("U-Vicente");

        cajaUVicente.setMinimumSize(new java.awt.Dimension(100, 25));
        cajaUVicente.setPreferredSize(new java.awt.Dimension(100, 25));
        cajaUVicente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaUVicenteActionPerformed(evt);
            }
        });

        jLabel16.setText("Grabacion");

        cajaGrabacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaGrabacionActionPerformed(evt);
            }
        });

        jLabel17.setText("Analogas");

        cajaCAnalogas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaCAnalogasActionPerformed(evt);
            }
        });

        jLabel18.setText("Discos");

        cajaDiscos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaDiscosActionPerformed(evt);
            }
        });

        jLabel19.setText("Camáras IP");

        cajaCIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaCIPActionPerformed(evt);
            }
        });

        jLabel20.setText("P-Vicente");

        cajaPVicente.setMinimumSize(new java.awt.Dimension(100, 25));
        cajaPVicente.setPreferredSize(new java.awt.Dimension(100, 25));
        cajaPVicente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaPVicenteActionPerformed(evt);
            }
        });

        botonIngresoRest.setText("Ingreso");
        botonIngresoRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresoRestActionPerformed(evt);
            }
        });

        botonUpDateDvr.setText("UpDate");
        botonUpDateDvr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUpDateDvrActionPerformed(evt);
            }
        });

        botonBorrarDvr.setText("Borrar");
        botonBorrarDvr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarDvrActionPerformed(evt);
            }
        });

        cajaIdDvr.setEditable(false);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        cajaTipoCamara.setMinimumSize(new java.awt.Dimension(150, 25));
        cajaTipoCamara.setPreferredSize(new java.awt.Dimension(150, 25));

        jLabel22.setText("IP:");

        cajaUsuarioCamara.setMinimumSize(new java.awt.Dimension(150, 25));
        cajaUsuarioCamara.setPreferredSize(new java.awt.Dimension(150, 25));

        jLabel24.setText("Password:");

        jLabel23.setText("Usuario:");

        cajaIpCamara.setMinimumSize(new java.awt.Dimension(150, 25));
        cajaIpCamara.setPreferredSize(new java.awt.Dimension(150, 25));

        cajaPassCamara.setMinimumSize(new java.awt.Dimension(150, 25));
        cajaPassCamara.setPreferredSize(new java.awt.Dimension(150, 25));

        jLabel21.setText("Tipo:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "IP Cámara", "Usuario", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cajaTipoCamara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaUsuarioCamara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaIpCamara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaPassCamara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(281, 281, 281))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cajaTipoCamara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cajaUsuarioCamara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cajaIpCamara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cajaPassCamara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1327, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cajaIP, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cajaGrabacion, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cajaDiscos)
                            .addComponent(cajaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cajaCAnalogas))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(cajaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(cajaSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(cajaCIP)))
                        .addGap(18, 18, 18)
                        .addComponent(cajaIdDvr, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonUpDateDvr, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonIngresoRest, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(botonBorrarDvr, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(352, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(67, 67, 67)
                                                .addComponent(cajaUAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel3)
                                                .addGap(18, 18, 18)
                                                .addComponent(cajaPAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel4))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addGap(18, 18, 18)
                                                .addComponent(cajaUVicente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel20)
                                                .addGap(18, 18, 18)
                                                .addComponent(cajaPVicente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel7)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cajaUAlejandro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cajaUGerente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cajaPGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(18, 18, 18)
                                                .addComponent(cajaPAlejandro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cajaUMario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cajaUOtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(cajaPOtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cajaPMario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(37, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jLabel1)
                        .addComponent(cajaIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(cajaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonIngresoRest))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(cajaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(cajaSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cajaIdDvr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cajaGrabacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(cajaDiscos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(cajaCIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaCAnalogas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonUpDateDvr)
                    .addComponent(botonBorrarDvr)
                    .addComponent(jLabel17))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(cajaUAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(cajaPAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(cajaUAlejandro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(cajaPAlejandro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(cajaUMario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)
                        .addComponent(cajaPMario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cajaUVicente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(cajaPVicente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cajaUGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cajaPGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaPOtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cajaUOtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Principal a = new Principal();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        mostrarTablaDvr(idRestDvr);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void cajaIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaIPActionPerformed

    private void cajaUAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaUAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaUAdminActionPerformed

    private void cajaPAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaPAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaPAdminActionPerformed

    private void cajaUAlejandroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaUAlejandroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaUAlejandroActionPerformed

    private void cajaPAlejandroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaPAlejandroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaPAlejandroActionPerformed

    private void cajaUMarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaUMarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaUMarioActionPerformed

    private void cajaUGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaUGerenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaUGerenteActionPerformed

    private void cajaPGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaPGerenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaPGerenteActionPerformed

    private void cajaUOtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaUOtroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaUOtroActionPerformed

    private void cajaPOtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaPOtroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaPOtroActionPerformed

    private void cajaMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaMarcaActionPerformed

    private void cajaModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaModeloActionPerformed

    private void cajaPMarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaPMarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaPMarioActionPerformed

    private void cajaSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaSerieActionPerformed

    private void cajaUVicenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaUVicenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaUVicenteActionPerformed

    private void cajaGrabacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaGrabacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaGrabacionActionPerformed

    private void cajaCAnalogasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaCAnalogasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaCAnalogasActionPerformed

    private void cajaDiscosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaDiscosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaDiscosActionPerformed

    private void cajaCIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaCIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaCIPActionPerformed

    private void cajaPVicenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaPVicenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaPVicenteActionPerformed

    private void botonIngresoRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresoRestActionPerformed
        IngresarDvr(idRestDvr);

    }//GEN-LAST:event_botonIngresoRestActionPerformed

    private void botonUpDateDvrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUpDateDvrActionPerformed
        upDateDvr();
    }//GEN-LAST:event_botonUpDateDvrActionPerformed

    private void botonBorrarDvrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarDvrActionPerformed
        borrarDvr();
    }//GEN-LAST:event_botonBorrarDvrActionPerformed

    private void tablaDvrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDvrMouseClicked
        
        mostrarCajas();

    }//GEN-LAST:event_tablaDvrMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDVR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDVR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDVR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDVR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDVR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBorrarDvr;
    private javax.swing.JButton botonIngresoRest;
    private javax.swing.JButton botonUpDateDvr;
    private javax.swing.JTextField cajaCAnalogas;
    private javax.swing.JTextField cajaCIP;
    private javax.swing.JTextField cajaDiscos;
    private javax.swing.JTextField cajaGrabacion;
    private javax.swing.JTextField cajaIP;
    private javax.swing.JTextField cajaIdDvr;
    private javax.swing.JTextField cajaIpCamara;
    private javax.swing.JTextField cajaMarca;
    private javax.swing.JTextField cajaModelo;
    private javax.swing.JTextField cajaPAdmin;
    private javax.swing.JTextField cajaPAlejandro;
    private javax.swing.JTextField cajaPGerente;
    private javax.swing.JTextField cajaPMario;
    private javax.swing.JTextField cajaPOtro;
    private javax.swing.JTextField cajaPVicente;
    private javax.swing.JTextField cajaPassCamara;
    private javax.swing.JTextField cajaSerie;
    private javax.swing.JTextField cajaTipoCamara;
    private javax.swing.JTextField cajaUAdmin;
    private javax.swing.JTextField cajaUAlejandro;
    private javax.swing.JTextField cajaUGerente;
    private javax.swing.JTextField cajaUMario;
    private javax.swing.JTextField cajaUOtro;
    private javax.swing.JTextField cajaUVicente;
    private javax.swing.JTextField cajaUsuarioCamara;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tablaDvr;
    // End of variables declaration//GEN-END:variables

    public void mostrarTablaDvr(int x) {

        DefaultTableModel modeloTabla = new DefaultTableModel();
        tablaDvr.setModel(modeloTabla);

        PreparedStatement ps = null;
        ResultSet rs = null;

        try {
            Conexion con = new Conexion();
            Connection conexion = con.getConnection();

            ps = conexion.prepareStatement("select ipdvr, usuarioadmin, passadmin, usuarioale, passale, usuariomario, passmario, usuariovi, passvi, usuarioger, passger, usuariootro, passotro, marcadvr, modelodvr, seriedvr, capacidadgrabacion, discos, camarasanalogas, camarasip from dvr where idrest = " + x);
            rs = ps.executeQuery();
            System.out.println(x + "id restaurante");

            //establecer columnas
            modeloTabla.addColumn("IP");
            modeloTabla.addColumn("U-Admin");
            modeloTabla.addColumn("P-Admin");
            modeloTabla.addColumn("U-Ale");
            modeloTabla.addColumn("P-Ale");
            modeloTabla.addColumn("U-Mario");
            modeloTabla.addColumn("P-Mario");
            modeloTabla.addColumn("U-Vic");
            modeloTabla.addColumn("P-Vic");
            modeloTabla.addColumn("U-Ger");
            modeloTabla.addColumn("P-Ger");
            modeloTabla.addColumn("U-Otro");
            modeloTabla.addColumn("P-Otro");
            modeloTabla.addColumn("Marca");
            modeloTabla.addColumn("Model");
            modeloTabla.addColumn("SN");
            modeloTabla.addColumn("Cap.Grab");
            modeloTabla.addColumn("Cap.Discos");
            modeloTabla.addColumn("C-Analogas");
            modeloTabla.addColumn("C-IP");

            ResultSetMetaData rsMD = rs.getMetaData();
            int cantidadColumnas = rsMD.getColumnCount();
            System.out.println(cantidadColumnas);

            //tamaño de las columnas
            int anchos[] = {30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 10, 10};

            for (int i = 0; i < cantidadColumnas; i++) {
                tablaDvr.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
            }

            //agregar filas
            while (rs.next()) {
                Object fila[] = new Object[cantidadColumnas];

                for (int i = 0; i < cantidadColumnas; i++) {
                    fila[i] = rs.getObject(i + 1);
                }

                modeloTabla.addRow(fila);
                System.out.println(fila);
            }

            rs.close();
        } catch (Exception ex) {
            System.err.println("Error, " + ex);
        }

    }//final mostrarTablaDvr
    
    public void mostrarCajas(){
               PreparedStatement ps=null;
        ResultSet rs=null;
        
        try{
            Conexion con = new Conexion();
            Connection conexion = con.getConnection();
            
            int fila = tablaDvr.getSelectedRow();
            String codigo = tablaDvr.getValueAt(fila, 0).toString();
            
            ps = conexion.prepareStatement("select iddvr, ipdvr, usuarioadmin, passadmin, usuarioale, passale, usuariomario, passmario, usuariovi, passvi, usuarioger, passger, usuariootro, passotro, marcadvr, modelodvr, seriedvr, capacidadgrabacion, discos, camarasanalogas, camarasip from dvr where ipdvr = ? ");
            ps.setString(1, codigo);
          
            
            rs = ps.executeQuery();
            System.out.println(codigo);
            
            while(rs.next()){
                
                cajaIdDvr.setText(rs.getInt("iddvr")+"");
               cajaIP.setText(rs.getString("ipdvr"));
            cajaUAdmin.setText(rs.getString("usuarioadmin"));
            cajaPAdmin.setText(rs.getString("passadmin"));
            cajaUAlejandro.setText(rs.getString("usuarioale"));
            cajaPAlejandro.setText(rs.getString("passale"));
            cajaUMario.setText(rs.getString("usuariomario"));
            cajaPMario.setText(rs.getString("passmario"));
            cajaUVicente.setText(rs.getString("usuariovi"));
            cajaPVicente.setText(rs.getString("passvi"));
            cajaUGerente.setText(rs.getString("usuarioger"));
            cajaPGerente.setText(rs.getString("passger"));
            cajaUOtro.setText(rs.getString("usuariootro"));
            cajaPOtro.setText(rs.getString("passotro"));
            cajaMarca.setText(rs.getString("marcadvr"));
            cajaModelo.setText(rs.getString("modelodvr"));
            cajaSerie.setText(rs.getString("seriedvr"));
            cajaGrabacion.setText(rs.getInt("capacidadgrabacion")+"");
            cajaDiscos.setText(rs.getString("discos"));
            cajaCAnalogas.setText(rs.getInt("camarasanalogas")+"");
            cajaCIP.setText(rs.getInt("camarasip")+"");
            
            }
            
        }catch(Exception ex){
            System.err.println("Error, "+ex);
        }
    }//fin mostrar cajas

    private void IngresarDvr(int x) {

        Conexion con = new Conexion();
        Connection conexion = con.getConnection();

        PreparedStatement ps = null;
        ResultSet rs = null;

        try {
            ps = conexion.prepareStatement("insert into dvr (idrest, ipdvr, usuarioadmin, passadmin, usuarioale, passale, usuariomario, passmario, usuariovi, passvi, usuarioger, passger, usuariootro, passotro, marcadvr, modelodvr, seriedvr, capacidadgrabacion, discos, camarasanalogas, camarasip) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
            ps.setInt(1, x);
            ps.setString(2, cajaIP.getText());
            ps.setString(3, cajaUAdmin.getText());
            ps.setString(4, cajaPAdmin.getText());
            ps.setString(5, cajaUAlejandro.getText());
            ps.setString(6, cajaPAlejandro.getText());
            ps.setString(7, cajaUMario.getText());
            ps.setString(8, cajaPMario.getText());
            ps.setString(9, cajaUVicente.getText());
            ps.setString(10, cajaPVicente.getText());
            ps.setString(11, cajaUGerente.getText());
            ps.setString(12, cajaPGerente.getText());
            ps.setString(13, cajaUOtro.getText());
            ps.setString(14, cajaPOtro.getText());
            ps.setString(15, cajaMarca.getText());
            ps.setString(16, cajaModelo.getText());
            ps.setString(17, cajaSerie.getText());
            ps.setInt(18, Integer.parseInt(cajaGrabacion.getText()));
            ps.setString(19, cajaDiscos.getText());
            ps.setInt(20, Integer.parseInt(cajaCAnalogas.getText()));
            ps.setInt(21, Integer.parseInt(cajaCIP.getText()));

            int resultado = ps.executeUpdate();

            if (resultado > 0) {
                JOptionPane.showMessageDialog(null, "Ingresado");

            } else {
                JOptionPane.showMessageDialog(null, "No Ingresado");

            }

            conexion.close();

        } catch (Exception ex) {
            System.err.println("Error, " + ex);

        }

    }  // final del metodo IngresarDVR

    private void upDateDvr() {

        Conexion con = new Conexion();
        Connection conexion = con.getConnection();
        boolean confirmacion = true;

        PreparedStatement ps;
        ResultSet rs;

        try {

            ps = conexion.prepareStatement("update dvr set ipdvr=?, usuarioadmin=?, passadmin=?, usuarioale=?, passale=?, usuariomario=?, passmario=?, usuariovi=?, passvi=?, usuarioger=?, passger=?, usuariootro=?, passotro=?, marcadvr=?, modelodvr=?, seriedvr=?, capacidadgrabacion=?, discos=?, camarasanalogas=?, camarasip=? where iddvr = ?");

            ps.setString(1, cajaIP.getText());
            ps.setString(2, cajaUAdmin.getText());
            ps.setString(3, cajaPAdmin.getText());
            ps.setString(4, cajaUAlejandro.getText());
            ps.setString(5, cajaPAlejandro.getText());
            ps.setString(6, cajaUMario.getText());
            ps.setString(7, cajaPMario.getText());
            ps.setString(8, cajaUVicente.getText());
            ps.setString(9, cajaPVicente.getText());
            ps.setString(10, cajaUGerente.getText());
            ps.setString(11, cajaPGerente.getText());
            ps.setString(12, cajaUOtro.getText());
            ps.setString(13, cajaPOtro.getText());
            ps.setString(14, cajaMarca.getText());
            ps.setString(15, cajaModelo.getText());
            ps.setString(16, cajaSerie.getText());
            ps.setInt(17, Integer.parseInt(cajaGrabacion.getText()));
            ps.setString(18, cajaDiscos.getText());
            ps.setInt(19, Integer.parseInt(cajaCAnalogas.getText()));
            ps.setInt(20, Integer.parseInt(cajaCIP.getText()));
            ps.setInt(21, Integer.parseInt(cajaIdDvr.getText()));
            
            int resultado = ps.executeUpdate();

            if (resultado > 0) {
                JOptionPane.showMessageDialog(null, "Actualizado");

            } else {
                JOptionPane.showMessageDialog(null, "No Actualizado");

            }
        } catch (Exception ex) {
            System.err.println("Error, " + ex);
            JOptionPane.showMessageDialog(null, "No Actualizado");
        }

    }//final metodoto UpdateDVR
    
    
    
    public void borrarDvr(){
        
        Conexion con = new Conexion();
        Connection conexion = con.getConnection();

        PreparedStatement ps = null;
        ResultSet rs = null;

        try {
            ps = conexion.prepareStatement("delete from dvr where iddvr = ?");
            ps.setInt(1, Integer.parseInt(cajaIdDvr.getText()));
            

            int resultado = ps.executeUpdate();

            if (resultado > 0) {
                JOptionPane.showMessageDialog(null, "Eliminado");

            } else {
                JOptionPane.showMessageDialog(null, "No Eliminado");

            }

            conexion.close();

        } catch (Exception ex) {
            System.err.println("Error, " + ex);

        }
        
        
    }// final metodo borrarDvr
    
    

}//final
